swagger: '2.0'

info:
  version: "0.0.1"
  title: Python Flask REST API

consumes:
  - text/plain

produces:
  - application/json

paths:

  /generate_insights:
    get:
      operationId: get
      description: Get insights Confusion Matrix, Precision, Recall, Similarity
      responses:
        200:
          description: "insights Confusion Matrix, Precision, Recall, Similarity check response"
          schema:
            $ref: "#/definitions/generateInsightsResponse"
          examples:
            application/json: { "status": "running"}

  /status_insights:
    get:
      operationId: get
      description: Get status Confusion Matrix, Precision, Recall, Similarity
      responses:
        200:
          description: "status Confusion Matrix, Precision, Recall, Similarity check response"
          schema:
            $ref: "#/definitions/statusInsightsResponse"
          examples:
            application/json: { "status": "finished"}

  /generate_time_series_plots:
    get:
      operationId: get
      description: Get generate outliers graphs temporary
      responses:
        200:
          description: "generate outliers graphs temporary"
          schema:
            $ref: "#/definitions/generateTimeSeriesPlotsResponse"
          examples:
            application/json: { "status": "running"}

  /status_time_series_plots:
    get:
      operationId: get
      description: Get status outliers graphs temporary
      responses:
        200:
          description: "status outliers graphs temporary"
          schema:
            $ref: "#/definitions/statusTimeSeriesPlotsResponse"
          examples:
            application/json: { "status": "finished"}

  /generate_ngrams:
    get:
      operationId: get
      description: Get generate ngrams
      responses:
        200:
          description: "status generate ngrams"
          schema:
            $ref: "#/definitions/generateNgramsResponse"
          examples:
            application/json: {
              "monograms": [
              ["vivo",1003],
              ["recarga",625]
              ],
              "bigrams": [
              ["fazer recarga",385],
              ["vivo movel",286],
              ],
              "trigrams": [
              ["consultar consumo internet",46],
              ["quero fazer recarga",28]
              ]
            }

definitions:

  generateInsightsResponse:
    type: "object"
    properties:
      status:
        type: "string"

  statusInsightsResponse:
    type: "object"
    properties:
      status:
        type: "string"

  generateTimeSeriesPlotsResponse:
    type: "object"
    properties:
      status:
        type: "string"

  statusTimeSeriesPlotsResponse:
    type: "object"
    properties:
      status:
        type: "string"

  generateNgramsResponse:
    type: "object"
    properties:
      status:
        type: "string"
